name: CI

on:
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - "2.6"
          - "2.7"
          - "3.0"
          - "3.1"
        appraisal:
          - activemodel-5
          - activemodel-5_1
          - activemodel-5_2
          - activemodel-6_0
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Install dependencies
        run: |
          bundle install
          bundle exec appraisal install

      - name: Run tests
        env:
          TZ: America/New_York
        run: bundle exec appraisal ${{ matrix.appraisal }} rspec
